# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: alcaroff <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/07/24 16:48:25 by alcaroff          #+#    #+#              #
#    Updated: 2017/07/26 09:59:55 by alcaroff         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	@gcc -o ft_advanced_do-op do_op.c calculator.c ft.c
clean:
	@rm -f ft_advanced_do-op
re: clean all
