# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: alcaroff <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/07/23 14:46:21 by alcaroff          #+#    #+#              #
#    Updated: 2017/07/23 16:35:19 by alcaroff         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	gcc -Wall -Werror -Wextra -o rush2 srcs/main.c srcs/is_rush.c -I includes
clean: rush2
	rm rush2
re: clean all
rush00:
	gcc -Wall -Werror -Wextra -o rush0 srcs/rush00/main.c srcs/rush00/ft_putchar.c srcs/rush00/rush03.c -I includes
clean0:
	rm rush0

